#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

if [[ $(xrandr -q | grep 'DP-1 connected') ]]; then
	xrandr --output LVDS-1 --primary --auto --output DP-1 --mode 2560x1440 --right-of LVDS-1 &
fi

bspc monitor LVDS-1 -d 命令行 瀏覽器 Code 畫圖 V VI
bspc monitor DP-1 -d VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# auto start applications
nitrogen --restore &
polybar laptop-screen &
picom --config $HOME/.config/picom/picom.conf &
dunst &
fcitx5 -d &

